import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../style/global.css'
import { cn } from '@/lib/utils'
import Navbar from '../components/Navbar';
import { Toaster } from '@/components/ui/Toaster';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Talk_it',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={cn('bg-white text-slate-900 antialiased light',inter.className)}>
      <body className='pt-12 bg-slate-50 antialiased min-h-screen'>
        <Navbar/>
        <div className='container max-w-7xl auto h-full pt-12'>
          {children}
        </div>
        <Toaster/>
      </body>
    </html>
  )
}
